### ISSUE TITLE
怎么自定义graph model嘞

### ISSUE THREAD

**Issue by kikaendeavor** [jinzhanye/pokemon-diagram#1]
官方文档https://github.com/jgraph/mxgraph/tree/master/javascript/examples/grapheditor/www

绘制了很多很多组件，不知道结合vue后怎么调用？

有木有相关示例

**Comment by luobogor** [comment]
『自定义graph model』是什么意思，可以举个例子说明

**Comment by kikaendeavor** [comment]
类似这些

![image](https://user-images.githubusercontent.com/2987889/60089392-f55ba280-9772-11e9-8ad3-c6303959d1e1.png)

**Comment by luobogor** [comment]
可以参考这个例子 https://github.com/jgraph/mxgraph/blob/master/javascript/examples/stencils.html
